name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
            target: 'x86_64-apple-darwin'
            arch: 'x64'
            os: 'macos'
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
            target: 'aarch64-apple-darwin'
            arch: 'arm64'
            os: 'macos'
          - platform: 'windows-latest'
            args: '--target x86_64-pc-windows-msvc'
            target: 'x86_64-pc-windows-msvc'
            arch: 'x64'
            os: 'windows'

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install frontend dependencies
      run: npm ci

    - name: Build frontend
      run: npm run build

    - name: Install Tauri CLI
      run: npm install -g @tauri-apps/cli@latest

    - name: Tauri info (debugging aid)
      run: tauri info || true

    - name: Build Tauri app
      run: tauri build ${{ matrix.args }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
        TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}

    - name: Zip macOS .app bundle
      if: matrix.os == 'macos'
      run: |
        cd src-tauri/target/${{ matrix.target }}/release/bundle/macos
        zip -r ../../../../../macos-${{ matrix.arch }}.zip *.app

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}
        path: |
          src-tauri/target/${{ matrix.target }}/release/bundle/**/*.dmg
          src-tauri/target/${{ matrix.target }}/release/bundle/**/*.msi
          src-tauri/target/${{ matrix.target }}/release/bundle/**/*.exe
          macos-${{ matrix.arch }}.zip
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Show full artifact paths
      run: find artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/**/*.dmg
          artifacts/**/*.msi
          artifacts/**/*.exe
          artifacts/**/*.zip
        body: |
          ## Personal Assistant v${{ github.ref_name }}

          ### 📦 Downloads
          - **macOS (Intel)**: Download `.dmg` or `.zip`
          - **macOS (Apple Silicon)**: Download `.dmg` or `.zip`
          - **Windows**: Download `.msi` or `.exe`

          ### 🚀 Features
          - AI-powered document search and chat
          - Activity monitoring and productivity tracking
          - Goal setting and progress tracking
          - Local data storage (privacy-first)
          - Multi-format document processing

          ### 📋 Prerequisites
          1. **Ollama**: `curl -fsSL https://ollama.ai/install.sh | sh`
          2. **AI Models**: `ollama pull nomic-embed-text && ollama pull llama3.2:1b`
          3. **Qdrant** (optional): `docker run -p 6333:6333 qdrant/qdrant`

          ### 🔧 Installation
          See [INSTALLATION.md](INSTALLATION.md) for setup instructions.

          ### 📝 Changelog
          - Enhanced document processing with pdf-extract fallback
          - Improved RAG system with Qdrant integration
          - Activity monitoring with goal tracking
          - Multi-model LLM support
          - Better error handling and logging
          - Fixed build issues and icon packaging

        draft: false
        prerelease: ${{ contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}